# Site settings

title: Jun and LaLa
email: 394900197@qq.com

description: > # this means to ignore newlines until "baseurl:"
  This my first try to write down a blog for recording my daily life.
  It is about my study on WEB and my story with Lala~
baseurl: /blogForLala # the subpath of your site, e.g. /blog/

url: "http://qianyongjun.github.io/blogForLala" # the base hostname & protocol for your site
# twitter_username: qianyongjun
github_username:  qianyongjun
# Build settings

markdown: kramdown
kramdown:
    input: GFM

collections:
  - tech
  - life
exclude:
  - vendor
# 设置多说评论
comments :
  provider : duoshuo
  duoshuo :
    short_name : Junjun and Lala
